(define (make-acc balance password)
  (lambda (pass sele)
    (cond ((not (eq? pass password)) "Wrong Password")
          ((eq? sele 'deposit)
           (lambda (amount)
             (set! balance (+ balance amount))
             balance))
          ((eq? sele 'withdraw)
           (lambda (amount)
             (if (> balance amount)
                 (begin 
                   (set! balance (- balance amount))
                   balance)
                 "Too few money" )))
          (else "Bad selector"))))

(define (make-acc1 balance password)
  (lambda (pass sele amount)
    (cond ((not (eq? pass password)) "wrong pass")
          ((eq? sele 'deposit)
           (begin (set! balance (+ balance amount))
             balance))
          ((eq? sele 'withdraw)
           (if (> balance amount)
               (begin (set! balance (- balance amount))
                 balance)
               "too few cash"))
          (else "badoviy selector"))))
                   