(define (make-acc2 balance password)
  (let ((count 0))
    (lambda (pass sele amount)
      (if (eq? pass password)
          (begin (set! count 0)
          (cond ((eq? sele 'depo)
                 (begin (set! balance (+ balance amount))
                   balance))
                ((eq? sele 'minus)
                 (if (>= balance amoun)
                     (begin (set! balance (- balance amount))
                       balance)))
                (else 'UnknownSelector)))
          (begin (set! count (+ count 1))
               (if (>= count 3)
                   (call-the-police)
                   'WrongPass))))))
           
             